bookingsystem/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :bookings
  resources :rooms
  resources :days
  resources :waitinglits

  root to: 'days#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookingsystem/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room, optional: true
  belongs_to :day,  optional: true
  validates :room_id, :participants, :email, :date, :starttime, :endtime, :importance, :category, presence: true
end

bookingsystem/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all.order("id ASC")
    @rooms = Room.all.order("id ")
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @bookings = Booking.find(params[:id])
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit

  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    @booking.user_id = current_user.id
    @booking.save

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json

  # if @booking.starttime != @booking.endtime
  # else
  # end

  def update
    if @booking.starttime == @booking.endtime
      @booking.endtime + 1
    end
    if user_signed_in?
      @booking.status = "BOOKED"
      @booking.user_id = current_user.id

    else
      @booking.status = "PENDING"
      @booking.user_id = 1
    end



    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end


  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params

      params.require(:booking).permit(:user_id, :name, :room_id, :participants, :email, :date, :starttime, :endtime, :importance, :category,:note, :status )

    end
end

bookingsystem/app/helpers/bookings_helper.rb
module BookingsHelper
end

bookingsystem/app/views/bookings/_form.html.erb
<%= stylesheet_link_tag "bookings" %>

<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_box">
    <div class="field">
        <%= form.label :Name, class:"namefield" %>
        <!-- Default value of textbox is User 1 if not logged in -->
        <!-- Otherwise if logged in the textbox will display only the user logged in -->
        <%= form.text_field :name, placeholder: "Please Enter A Name...", class: "userinput" %>
      </div>

      <div class="field">

        <%= form.label :Email, class:"namefield"%>
        <%= form.text_field :email, placeholder: "example@spartaglobal.com?", class: "userinput" %>
      </div>

      <div class="field">
        <%= form.label :Room_name, class:'roomfield' %>
        <%= collection_select(:booking, :room_id, Room.all, :id, :room_name) %>
      </div>

        <div class="field">
          <p><%= form.label :Participants, class:'participantsfield' %>
          <%= form.number_field :participants, :class => 'text_field', in: 1..15 %> Members</p>
        </div>

    <div class="field">
      <%= form.label :Start, class:"startfield" %>
      <%= form.select(:starttime, options_for_select([['8am', 8], ['9am', 9], ['10am', 10],
        ['11am', 11], ['12pm', 12], ['1pm', 13], ['2pm', 14],
        ['3pm', 15], ['4pm', 16], ['5pm', 17], ['6pm', 18]], :selected => @booking.starttime)) %>
    </div>

    <div class="field">
      <p><%= form.label :End, class:"endfield"%>
        <%= form.select(:endtime, options_for_select([['8am', 8], ['9am', 9], ['10am', 10],
          ['11am', 11], ['12pm', 12], ['1pm', 13], ['2pm', 14],
          ['3pm', 15], ['4pm', 16], ['5pm', 17], ['6pm', 18], ['7pm', 19]], :selected => @booking.starttime + 1)) %>
    </div>

    <div class="field">
      <%= form.label :Importance, class:"importancefield"%>
      <%= form.select(:importance, options_for_select([['Normal-!', '!'], ['Important-!!', '!!'],
        ['Urgent-!!!', '!!!']]), {:prompt => "Select Importance"}) %>
    </div>

    <div class="field">
      <%= form.label :Category, class:"categoryfield" %>
      <%= form.select(:category, options_for_select([['Face-to-Face Interview', 'Face-to-Face Interview'], ['Phone Interview', 'Phone Interview'],
        ['Mock exams', 'Mock exams'], ['Exams', 'Exams'], ['Presentation Rehersal', 'Presentation Rehersal'],
        ['1-On-1', '1-On-1'], ['Client Visit', 'Client Visit'], ['Management Meeting', 'Management Meeting'],
        ['Sparta Day', 'Sparta Day'], ['Other', 'Other']]), {:prompt => "Select Category"} )%>
    </div>

    <div class="field">
      <%= form.label :Additional_Notes %>
      <%= form.text_area :note, placeholder: "Additional Notes About The Meeting..." %>
    </div>

    <% if user_signed_in? && current_user.id ==2%>
    <div class="field">
      <%= form.label :Status %>
      <%= form.select(:status, options_for_select([['AVAILABLE', 'AVAILABLE'], ['PENDING', 'PENDING'],
        ['BOOKED', 'BOOKED']]), {:prompt => "Select status"} )%></div>
      <%end%>
      <div class="actions day_label">

        <%= form.submit "Book Room", class: "userinput" %>



    </div>
  </div>







<% end %>

bookingsystem/app/views/bookings/edit.html.erb
<h1 class="edit_heading">Edit Booking</h1>

<%= render 'form', booking: @booking %>



<%= link_to 'Back', day_path(@booking.day_id), :class => "back_button" %>

bookingsystem/app/views/bookings/index.html.erb
<%= stylesheet_link_tag "bookings" %>
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>


<div class="timing">
  <table>
    <th>Time</th>
    <tr><td>08:00</td></tr>
    <tr><td>09:00</td></tr>
    <tr><td>10:00</td></tr>
    <tr><td>11:00</td></tr>
    <tr><td>12:00</td></tr>
    <tr><td>13:00</td></tr>
    <tr><td>14:00</td></tr>
    <tr><td>15:00</td></tr>
    <tr><td>16:00</td></tr>
    <tr><td>17:00</td></tr>
    <tr><td>18:00</td></tr>
    <tr><td>19:00</td></tr>


  </table>
</div>
<div>
<table>
  <thead>
    <tr>
    <% @rooms.each do |room| %>
      <th><%=room.room_name%></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
        <% if booking.id % 7 == 0%>
          <% if booking.status == "BOOKED" %>
            <tr></tr>
          <td class= <%= booking.room.room_name %>><%= link_to booking.inspect, edit_booking_path(booking) %></td>
          <% else %>
              <tr></tr>
              <td><%= link_to booking.starttime, booking_path(booking) %></td>
          <% end %>
        <%else%>
          <% if booking.status =="BOOKED" %>
            <td class= <%= booking.room.room_name %>><%= link_to booking.inspect, edit_booking_path(booking) %></td>
            <% else %>
              <td><%= link_to 'book', booking_path(booking) %><%= booking.user_id %></td>
          <% end %>
        <%end%>
    <% end %>
  </tbody>
</table>
</div>

<% if user_signed_in? && current_user.id ==2%>
  <div class="waiting">
    <table>
      <th class="list_size">Waitinglist</th>
      <% @bookings.each do |booking| %>
      <%if booking.status == "PENDING"%>
        <tr><td class="list_size"><%=booking.name%></td></tr>
        <%end%>
      <%end%>
    </table>
  </div>
<%end%>
  <br>
</div>

bookingsystem/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

bookingsystem/app/views/bookings/show.html.erb
<%= stylesheet_link_tag "bookings" %>

<p id="notice"><%= notice %></p>

<h1 class="edit_heading">View Booking</h1>

<div class="show_box">
  <p>
    <strong>Name:</strong>
    <%= @booking.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @booking.email %>
  </p>

  <p>
    <strong>Room Name:</strong>
    <%= @booking.room.room_name %>
  </p>

  <p>
    <strong>Participants:</strong>
    <%= @booking.participants %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @booking.date %>
  </p>

  <p>
    <strong>Start Time:</strong>
    <%= @booking.starttime%>
  </p>

  <p>
    <strong>End Time:</strong>
    <% if @booking.starttime == @booking.endtime %>
    <% @booking.endtime = @bookings.endtime + 1 %>
    <%= @booking.endtime %>
    <% else %>
    <%= @booking.endtime %>
    <% end %>
  </p>

  <p>
    <strong>Importance:</strong>
    <%= @booking.importance %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @booking.category %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @booking.note %>
  </p>
</div>


<%= link_to 'Back', day_path(@booking.day_id), :class => "back_button" %>