bookingsystem/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :bookings
  resources :rooms
  resources :days
  resources :waitinglits

  root to: 'days#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookingsystem/app/models/day.rb
class Day < ApplicationRecord
  has_many :bookings
  has_many :rooms, :through => :bookings

end

bookingsystem/app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @call = Day.all
    @days = Day.find(params[:id])
    @bookings = @days.bookings.all.order("id DESC")
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.fetch(:day, {})
    end
end

bookingsystem/app/helpers/days_helper.rb
module DaysHelper
end

bookingsystem/app/views/days/_form.html.erb
<%= form_with(model: day, local: true) do |form| %>
  <% if day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

bookingsystem/app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

bookingsystem/app/views/days/index.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag "bookings" %>
<%= stylesheet_link_tag "application" %>

<h1>August</h1>
  <table id='calendar'>
   <tr>
     <th class="day_label">Sunday</th><th class="day_label">Monday</th>
     <th class="day_label">Tuesday</th><th class="day_label">Wednesday</th>
     <th class="day_label">Thursday</th><th class="day_label">Friday</th>
     <th class="day_label">Saturday</th>
    </tr>
    <tr>
      <% i = 0 %>
      <% u = 0 %>

      <% day_store = {} %>

      <% @days.each do |day| %>
        <%  day_store[i] = day %>
        <%  i += 1 %>
      <% end %>

    <% @beginning_of_month = Date.current.beginning_of_month %>
    <% @end_of_month = Date.current.end_of_month %>

  <% (@beginning_of_month..@end_of_month).each do |d| %>
      <% if d == @beginning_of_month %>
        <% d.wday.times do %> <td class='offset'></td> <% end %>
      <% end %>


  <% if d.wday == 0 %> </tr><tr> <% end %>
    <td class="day"> <%= link_to d.day, day_store[u], class: "day_main" %> </td>
    <% u += 1 %>
  <% end %>

    </tr>
  </table>

bookingsystem/app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Back', days_path %>

bookingsystem/app/views/days/show.html.erb
<!-- start  -->


<%= stylesheet_link_tag "bookings" %>
<p id="notice"><%= notice %></p>

  <div class="container " id="call">
    <div class="row">
      <div class="span12">
        <table class="table-condensed table-bordered table-striped">
          <thead>
            <tr>
              <th colspan="7">
                <span class="btn-group">
                  <a class="btn">
                    <i class="icon-chevron-left"></i>
                  </a>
                  <a class="btn active">Month</a>
                  <a class="btn">
                    <i class="icon-chevron-right"></i>
                  </a>
                </span>
              </th>
            </tr>
            <tr>
              <th>Mo</th>
              <th>Tu</th>
              <th>We</th>
              <th>Th</th>
              <th>Fr</th>
              <th>Sa</th>
              <th>Su</th>
            </tr>
          </thead>
          <tbody>
            <% x = 0 %>

              <% @call.each do |day| %>
              <% if x%7 ==0 %>
              </tr>
            <% end %>

                  <td class="day">

                    <%= link_to day.id, day %>
                  </td>

                <% x += 1 %><%  end  %>


              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>



<h1 class="heading">Bookings</h1>
<div class="full_display">
  <div class="timing">
    <table>
      <th>Time</th>
      <tr><td class="timeslot">8:00</td></tr>
      <tr><td class="timeslot">9:00</td></tr>
      <tr><td class="timeslot">10:00</td></tr>
      <tr><td class="timeslot">11:00</td></tr>
      <tr><td class="timeslot">12:00</td></tr>
      <tr><td class="timeslot">13:00</td></tr>
      <tr><td class="timeslot">14:00</td></tr>
      <tr><td class="timeslot">15:00</td></tr>
      <tr><td class="timeslot">16:00</td></tr>
      <tr><td class="timeslot">17:00</td></tr>
      <tr><td class="timeslot">18:00</td></tr>
      <tr><td class="timeslot">19:00</td></tr>


    </table>
  </div>

  <table>
    <thead>
      <tr>
        <th class="zeldaheading">Zelda</th>
        <th class="marioheading">Mario</th>
        <th class="pacmanheading">Pac-Man</th>
        <th class="froggerheading">Frogger</th>
        <th class="cortanaheading">Cortana</th>
        <th class="tetrisheading">Tetris</th>
        <th class="breakoutheading">Breakout</th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
      <% if booking.id % 7 == 0%>
        <% if booking.status =="BOOKED" || booking.status =="PENDING"  %>
        <tr></tr>
          <%if user_signed_in? && current_user.id ==2%>
          <td class= <%= booking.room.room_name %>><%= link_to booking.status, edit_booking_path(booking) %></td>
          <%else%>
            <td class= <%= booking.room.room_name %>><%= link_to booking.status, booking_path(booking) %></td>
          <%end%>
        <% else %>
        <tr></tr>
            <td class="booking_field"><%=link_to booking.status, edit_booking_path(booking), :class => "booking_field" %></td>
        <% end %>
      <%else%>
        <% if booking.status =="BOOKED"  || booking.status =="PENDING"%>
          <%if user_signed_in? && current_user.id ==2%>
            <td class= <%= booking.room.room_name %>><%= link_to booking.status, edit_booking_path(booking) %></td>
          <%else%>
            <td class= <%= booking.room.room_name %>><%= link_to booking.status, booking_path(booking) %></td>
          <%end%>
        <% else %>
            <td class="booking_field"><%= link_to booking.status, edit_booking_path(booking), :class => "booking_field" %></td>
        <% end %>
      <%end%>
    <% end  %>
    </tbody>
  </table>

  <br>
</div>

<%if user_signed_in? && current_user.id ==2%>
  <div class="waiting">
    <table>
      <th class="waiting_heading list_size">Waiting List</th>
      <% @bookings.each do |booking| %>
      <%if booking.status == "PENDING"%>
        <tr><td class="waiting_heading"><%=booking.room.room_name%> |<%= link_to booking.name, edit_booking_path(booking)%></td></tr>
        <%end%>
      <%end%>
    </table>
<%end%>
</div>